### ISSUE TITLE
Docs examples are deprecated

### ISSUE THREAD

**Issue by itsTyrion** [VelocityPowered/documentation#12]
A lot of things from the docs are pretty outdated (API version 1.0.0)
The first few examples provided use deprecated code, the non-deprecated version doesn't seem to be documented?

net.kyori.text.TextComponent -> net.kyori.adventure.text.Component
net.kyori.text.format.TextColor -> net.kyori.adventure.text.format.NamedTextColor/net.kyori.adventure.text.format.TextColor.color(int)
com.velocitypowered.api.command.Command#execute(CommandSource,String[]) -> com.velocitypowered.api.command.SimpleCommand#execute(Invocation)

**Comment by A248** [comment]
you ought to use https://velocitypowered.com/wiki/ in preference to docs.velocitypowered.com

**Comment by astei** [comment]
`docs.velocitypowered.com` is no longer updated, the wiki at https://velocitypowered.com/wiki is the most up to date. I will be closing the site soon.
