### ISSUE TITLE
Having trouble with connecting to servers via DeluxHub-Compass

### ISSUE THREAD

**Issue by 10BamberJ** [VelocityPowered/documentation#9]
Hayy, I'm using velocity for bungee for my pixelmon server also I'm using it for my skyblock and factions and prison server. I'm having trouble adding the command to my compass  to allowing them to connect to the other servers. 

      pixelmon:
        Item: OAK_LEAVES
        Slot: 34
        Amount: 1
        Name: '&c&lPixelmon &8[&c1.12.2-Modded&8]'
        Lore:
          - '&7Online Players: &5&n%bungee_survival%'
          - '&r'
          - '&7Battle your friends with pokemons'
          - '&7Catch them all!'
          - '&r'
          - '&8Features:'
          - '&7* &5Use (Pixelmon Reforged)!'
          - '&7'
          - '&5&nRight-Click&7 to join the server!'
        Commands:
          - 'server pixelmon' //I've put [bungee] and tried [command]. Non of them work
          - '[message] &7Sending you to: &cPixelmon'

I've been looking for placeholders for you're pluing and I can not find anything on you're page. Can you help me at all. I have also sent this to deluxhub to see what they can do about this.

**Comment by jacoballen1** [comment]
1. This is the wrong place to post this issue, the correct place is on discord.
2. Velocity is _not_ a plugin, and is not Bungeecord.

If you still require assistance, I suggest posting your issue into the support channel on discord.

**Comment by astei** [comment]
Closing, this is off-topic for the documentation repo.
